version: "2.2"

services:
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/click_storm/
    ports:
      - 80:80
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=AXQEZOPADO
      - POSTGRES_DB=ClickStorm
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935

volumes:
  postgres_data:
